
addr = '185.15.201.102'

addr_priv = '192.168.103.250'

allow_agent = true

clienttype = ''

forward_agent = true

login = 'root'

passwd_ = ''

port = 2200

port_priv = 22

proxy = ''

sshkey = 'mykey'

stdout = true

timeout = 300
