
addr = '192.168.2.1'

addr_priv = ''

allow_agent = true

clienttype = ''

forward_agent = true

login = 'root'

passwd_ = ''

port = 22

port_priv = 22

proxy = ''

sshkey = ''

stdout = true

timeout = 5
