
addr = '129.12.54.54'

addr_priv = ''

allow_agent = true

clienttype = ''

forward_agent = true

login = ''

passwd_ = ''

port = 22

port_priv = 22

proxy = ''

sshkey = ''

stdout = true

timeout = 5
