
active = true

category = 'openvcloud'

clienttype = 'j.clients.openvcloud'

description = 'deployment in openvcloud'

installed = false

name = 'tmpmac'

pubconfig = '""'

secretconfig_ = '""'

selected = false

sshclient = '10-101-107-144-2208-root-public'

zosclient = ''
